### ISSUE TITLE
[Error Handler] Rework

### ISSUE THREAD

**Issue by Aluerie** [Aluerie/AluBot#10]
Current Error Handler is a chaoric order tier mess. 

We need to rewrite it. 

# TODO

- [ ] Rewrite all Clr.error into raise Error
- [ ] Look at Ctrl Shift F `#TODO` - a lot of these are about bad Error Exception classes
- [ ] Create our own error like AluException so we know I raised it and not discord lib. 
- [ ] I think we should put error handler somewhere at utils folder instead of having it at cogs. 
- [ ] Check all situations like `cog_error`, text/slash, etc. 

### Sources to consult at

* Check DuckBot guys
  * They have it in utils folder which is a great place for error handler, actually. 
* Rdanny is a classic, but I think his error handler structure is super chaos.
  * `on_app_command_error` in stats cog
  * `on_command_error` in bot
  * and overall cog and command errors thrown around

* there is also this :D https://github.com/aurkaxi/spoonfeed-dpy
