### ISSUE TITLE
[FPC] TODO LIST

### ISSUE THREAD

**Issue by Aluerie** [Aluerie/AluBot#17]
- [ ] Auto-generation of cogs.
  Rework your stuff so both dota/lol/future generate their cogs automatically based on `__init__` arguments. Idk how, some magic with `add-command` maybe?
- [x] (?) add `/dota hero setup` menu for players
- [x] add icons to dota/lol heroes as emotes in `/dota hero setup`
- [x] decide how to get rid of slash/text duality
    * combine the concept of slash/text commands with no cares if slash commands work
    * remove auto-complete versions of the commands and only leave interactive views setup
    * instead of "working" when got text command - send "warning sorry you better use slash command"
    * new ideas, pepega
 - [ ] add database player maybe learn to accept dotabuff/opendota links ?
