### ISSUE TITLE
[MimicUsers] with Webhooks

### ISSUE THREAD

**Issue by Aluerie** [Aluerie/AluBot#18]
# TODO:

- [ ] ContextMenu command to delete the webhook message 
  - [ ] if same user, of course
  - [ ] Expiring cache with `message.id` - `user.id` relation. 
 - [ ] maybe we need database table with guild -> channel -> webhook relation
 - [ ] cache for that^
 - [ ] all possible permissions failure check?
